version: 0.0
os: linux
files:
  - source: discord-bot-cdk/discord-bot/
    destination: /opt/bitnami/discord-bot
hooks:
  ApplicationStop:
    - location: scripts/stop_bot.sh
      timeout: 60
      runas: bitnami
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: bitnami
  ApplicationStart:
    - location: scripts/start_bot.sh
      timeout: 300
      runas: bitnami
